// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/parser.proto

package parserpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VacancyParser_StartParsing_FullMethodName = "/parser.VacancyParser/StartParsing"
)

// VacancyParserClient is the client API for VacancyParser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VacancyParserClient interface {
	StartParsing(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error)
}

type vacancyParserClient struct {
	cc grpc.ClientConnInterface
}

func NewVacancyParserClient(cc grpc.ClientConnInterface) VacancyParserClient {
	return &vacancyParserClient{cc}
}

func (c *vacancyParserClient) StartParsing(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseResponse)
	err := c.cc.Invoke(ctx, VacancyParser_StartParsing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VacancyParserServer is the server API for VacancyParser service.
// All implementations must embed UnimplementedVacancyParserServer
// for forward compatibility.
type VacancyParserServer interface {
	StartParsing(context.Context, *ParseRequest) (*ParseResponse, error)
	mustEmbedUnimplementedVacancyParserServer()
}

// UnimplementedVacancyParserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVacancyParserServer struct{}

func (UnimplementedVacancyParserServer) StartParsing(context.Context, *ParseRequest) (*ParseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartParsing not implemented")
}
func (UnimplementedVacancyParserServer) mustEmbedUnimplementedVacancyParserServer() {}
func (UnimplementedVacancyParserServer) testEmbeddedByValue()                       {}

// UnsafeVacancyParserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VacancyParserServer will
// result in compilation errors.
type UnsafeVacancyParserServer interface {
	mustEmbedUnimplementedVacancyParserServer()
}

func RegisterVacancyParserServer(s grpc.ServiceRegistrar, srv VacancyParserServer) {
	// If the following call panics, it indicates UnimplementedVacancyParserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VacancyParser_ServiceDesc, srv)
}

func _VacancyParser_StartParsing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyParserServer).StartParsing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VacancyParser_StartParsing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyParserServer).StartParsing(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VacancyParser_ServiceDesc is the grpc.ServiceDesc for VacancyParser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VacancyParser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parser.VacancyParser",
	HandlerType: (*VacancyParserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartParsing",
			Handler:    _VacancyParser_StartParsing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/parser.proto",
}
