// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/parser.proto

package parserpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Company int32

const (
	Company_COMPANY_UNSPECIFIED Company = 0
	Company_COMPANY_VK          Company = 1
	Company_COMPANY_YANDEX      Company = 2
)

// Enum value maps for Company.
var (
	Company_name = map[int32]string{
		0: "COMPANY_UNSPECIFIED",
		1: "COMPANY_VK",
		2: "COMPANY_YANDEX",
	}
	Company_value = map[string]int32{
		"COMPANY_UNSPECIFIED": 0,
		"COMPANY_VK":          1,
		"COMPANY_YANDEX":      2,
	}
)

func (x Company) Enum() *Company {
	p := new(Company)
	*p = x
	return p
}

func (x Company) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Company) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_parser_proto_enumTypes[0].Descriptor()
}

func (Company) Type() protoreflect.EnumType {
	return &file_proto_parser_proto_enumTypes[0]
}

func (x Company) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Company.Descriptor instead.
func (Company) EnumDescriptor() ([]byte, []int) {
	return file_proto_parser_proto_rawDescGZIP(), []int{0}
}

type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       Company                `protobuf:"varint,1,opt,name=company,proto3,enum=parser.Company" json:"company,omitempty"`
	Direction     string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_proto_parser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_proto_parser_proto_rawDescGZIP(), []int{0}
}

func (x *ParseRequest) GetCompany() Company {
	if x != nil {
		return x.Company
	}
	return Company_COMPANY_UNSPECIFIED
}

func (x *ParseRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type ParseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"` // Support None/nil
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_proto_parser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_proto_parser_proto_rawDescGZIP(), []int{1}
}

func (x *ParseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ParseResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ParseResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

var File_proto_parser_proto protoreflect.FileDescriptor

const file_proto_parser_proto_rawDesc = "" +
	"\n" +
	"\x12proto/parser.proto\x12\x06parser\"W\n" +
	"\fParseRequest\x12)\n" +
	"\acompany\x18\x01 \x01(\x0e2\x0f.parser.CompanyR\acompany\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\"{\n" +
	"\rParseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12(\n" +
	"\rerror_message\x18\x03 \x01(\tH\x00R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_error_message*F\n" +
	"\aCompany\x12\x17\n" +
	"\x13COMPANY_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"COMPANY_VK\x10\x01\x12\x12\n" +
	"\x0eCOMPANY_YANDEX\x10\x022L\n" +
	"\rVacancyParser\x12;\n" +
	"\fStartParsing\x12\x14.parser.ParseRequest\x1a\x15.parser.ParseResponseB\"Z job-finder/proto/parser;parserpbb\x06proto3"

var (
	file_proto_parser_proto_rawDescOnce sync.Once
	file_proto_parser_proto_rawDescData []byte
)

func file_proto_parser_proto_rawDescGZIP() []byte {
	file_proto_parser_proto_rawDescOnce.Do(func() {
		file_proto_parser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_parser_proto_rawDesc), len(file_proto_parser_proto_rawDesc)))
	})
	return file_proto_parser_proto_rawDescData
}

var file_proto_parser_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_parser_proto_goTypes = []any{
	(Company)(0),          // 0: parser.Company
	(*ParseRequest)(nil),  // 1: parser.ParseRequest
	(*ParseResponse)(nil), // 2: parser.ParseResponse
}
var file_proto_parser_proto_depIdxs = []int32{
	0, // 0: parser.ParseRequest.company:type_name -> parser.Company
	1, // 1: parser.VacancyParser.StartParsing:input_type -> parser.ParseRequest
	2, // 2: parser.VacancyParser.StartParsing:output_type -> parser.ParseResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_parser_proto_init() }
func file_proto_parser_proto_init() {
	if File_proto_parser_proto != nil {
		return
	}
	file_proto_parser_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_parser_proto_rawDesc), len(file_proto_parser_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_parser_proto_goTypes,
		DependencyIndexes: file_proto_parser_proto_depIdxs,
		EnumInfos:         file_proto_parser_proto_enumTypes,
		MessageInfos:      file_proto_parser_proto_msgTypes,
	}.Build()
	File_proto_parser_proto = out.File
	file_proto_parser_proto_goTypes = nil
	file_proto_parser_proto_depIdxs = nil
}
